### ISSUE TITLE
SvelteKit development mode generates error messages.

### ISSUE THREAD

**Issue by andriytyurnikov** [vercel/speed-insights#31]
```
npm run dev
...
3:49:46 AM [vite] ✨ new dependencies optimized: @vercel/speed-insights/sveltekit
3:49:46 AM [vite] ✨ optimized dependencies changed. reloading
Error: Not found: /_vercel/speed-insights/vitals
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:483:13)
    at resolve (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:277:5)
    at #options.hooks.handle (/node_modules/@sveltejs/kit/src/runtime/server/index.js:49:56)
    at Module.respond (/node_modules/@sveltejs/kit/src/runtime/server/respond.js:274:40)

**Comment by smart** [comment]
I see this as well. I'm on sveltekit2.0 if that matters.

**Comment by smart** [comment]
Interesting the README says to put the initialization in your +layout.svelte file but the example has it in +layout.ts

**Comment by feugy** [comment]
Hello and thank you for the bug report.
I've fixed the README: the best way to use `injectSpeedInsights()` function is in the `+layout.ts/js` file (which will be run on server side), as per [our docs](https://vercel.com/docs/speed-insights/quickstart#call-the-injectspeedinsights-function-in-your-app)

However, I'm not seeing any error in console.
Could you please provide the version of `@vercel/speed-insights`  and sveltekit that you're using?

Thanks a million.
